name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-unit:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos-version: macos-15
            xcode-version: Xcode_16
    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 5
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode-version }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - run: |
          swift test --parallel --enable-code-coverage
